### ISSUE TITLE
classification job cancelled not valid hdf5 datatype

### ISSUE THREAD

**Issue by josemanuel097** [MStarmans91/WORC#2]
I tried to run a network classification task  and I got this message in the sink_data_.json file : 
  "classification": {
    "all": {
      "status": "JobState.cancelled", 
      "errors": [
        [
          "WORC_prostate_test___classify___all", 
          "JobState.failed", 
          "Encountered error: [FastrOutputValidationError] Output value [HDF5] \"vfs://tmp/prostate_test/classify/all/classification_0.hdf5\" not valid for datatype \"HDF5\" (/home/jose/anaconda3/envs/worc_pro/lib/python2.7/site-packages/fastr/execution/job.py:1087)", 
          "./classify/all/__fastr_result__.pickle.gz"

**Comment by MStarmans91** [comment]
Looking at your output, your temporary output of this WORC run is in the vfs://tmp/prostate_test folder. The error tells you that the output for the classify job, the sample called "all" (which is coincidentally the only sample run), the file "classification_0.hdf5" does not match the HDF5 datatype. 

This is an error reported by the fastr package and is very generic. If a job fails, the output is not generated. As the file does not exist, it is also not a valid output. In this case for the HDF5 datatype, but no file is also not compatible with other datatypes of course.

The error does not tell you what the actual error was why the output was not generated. I recommend going to the vfs://tmp/prostate_test/classify/all/ folder (in which vfs://tmp is your tmp fastr mount) and looking in the __fastr_stdout__.txt file. In there, you will find a calling command. Copying this to the command line and running will run the exact thing the fastr job was trying to execute and will thus give you the error produced.

**Comment by josemanuel097** [comment]
I did as you said and checked the the classify/all/folder and there was a mistake related to the way I upload my labels.
