### ISSUE TITLE
config.ini 

### ISSUE THREAD

**Issue by josemanuel097** [MStarmans91/WORC#5]
--I tried to use an specific type of  configuration on WORC , defined in a config.ini file , in my scrip I define it like this : 

config = ['/home/jtovar/worc_prostate/config_Melanoma_0830_0_original.ini'] or like this 
config = '/home/jtovar/worc_prostate/config_Melanoma_0830_0_original.ini

network.configs.append(config)

--When i run the scrip it gives me the same error: 

Traceback (most recent call last):
  File "worc_example.py", line 62, in <module>
    network.build()
  File "/home/jtovar/worc_prostate/worc_pro/lib/python2.7/site-packages/WORC/WORC.py", line 318, in build
    self.build_training()
  File "/home/jtovar/worc_prostate/worc_pro/lib/python2.7/site-packages/WORC/WORC.py", line 344, in build_training
    image_types.append(self.configs[c]['ImageFeatures']['image_type'])
TypeError: list indices must be integers, not str

**Comment by MStarmans91** [comment]
There was apparently a bug when using a .ini file instead of the configparser object from the WORC defaultconfig function. I fixed it and pushed it to the development branch: can you check if that fixed it?

**Comment by josemanuel097** [comment]
It worked, thanks!
