### ISSUE TITLE
Can we calculate the radiomic feature map using our WORC tool?

### ISSUE THREAD

**Issue by JZK00** [MStarmans91/WORC#70]
When we select the important features, we need to calculate the main radiomic feature map. I want to know can we implement the feature mapping by using our tool?

**Comment by MStarmans91** [comment]
Could you please decribe what you exactly mean by the main radiomics feature map and what you would require of such a map? There are different radiomics "maps" described in the literature, so I'm unsure which one you are referring to.

**Comment by MStarmans91** [comment]
Closed due to inactivity. @JZK00 feel free to open this again if you want to discuss this topic or sent me an email.
