### ISSUE TITLE
Use features_from_this_directory

### ISSUE THREAD

**Issue by bgielen** [MStarmans91/WORC#75]
Hi!

I try to use WORC using the features that I already extracted using PyRadiomics. I made hdf5 files for every patient containing the features using the example that you provided. However, when I run WORC it says that the first column should be patient, do I add the patient number as a feature value and feature label? 

![image](https://user-images.githubusercontent.com/100568957/224786168-fb22ae30-10e4-4887-979e-ac7b3085be55.png)

**Comment by bgielen** [comment]
Yes you are right, it was my label file. Thanks for you response! :)

**Comment by MStarmans91** [comment]
No problem, glad we found the problem.
