### ISSUE TITLE
Test with already trained workflow

### ISSUE THREAD

**Issue by bgielen** [MStarmans91/WORC#77]
I have run a couple of experiments and I was wondering whether it is possible to obtain the trained workflow and apply this workflow to a new dataset to see how the workflow performs on a new dataset?

**Comment by MStarmans91** [comment]
WORC saves the trained model, so in principle you can. But you would have to manually run this, i.e., manually run the preprocessing and features extraction, there is no easy way to do this using e.g. SimpleWORC or BasicWORC.

I would advice running WORC with separate predefined train and test set. In this way, you also get all the performance estimates, ROC curves etc on the test set. For more info (which I just updated), see https://worc.readthedocs.io/en/development/static/user_manual.html#training-and-test-sets

**Comment by MStarmans91** [comment]
Closed due to inactivity
